namespace: kamatera
name: kamatera
version: 0.0.1
readme: README.md
authors:
  - Ori Hoch
description: |
  Management of Kamatera cloud infrastructure
license: MIT
license_file: LICENSE
tags:
  - cloud
  - compute
repository: https://www.github.com/OriHoch/ansible-collection-kamatera
documentation: https://github.com/cloudwm/cwmtoolbox/blob/master/README.md
homepage: https://www.github.com/OriHoch/ansible-collection-kamatera
issues: https://www.github.com/OriHoch/ansible-collection-kamatera/issues
