namespace: kamatera
name: kamatera
version: 0.0.0
readme: README.md
authors:
  - Ori Hoch
description: |
  Management of Kamatera cloud infrastructure
license: MIT
tags:
  - cloud
  - compute
repository: https://www.github.com/cloudwm/ansible
documentation: https://github.com/cloudwm/ansible/blob/master/README.md
homepage: https://www.github.com/cloudwm/ansible
issues: https://www.github.com/cloudwm/ansible/issues
