namespace: kamatera
name: kamatera
version: 0.0.0
readme: README.md
authors:
  - Ori Hoch
description: |
  Management of Kamatera cloud infrastructure
license: MIT
tags:
  - cloud
  - compute
repository: https://www.github.com/Kamatera/ansible-collection-kamatera
documentation: https://github.com/Kamatera/ansible-collection-kamatera/blob/master/README.md
homepage: https://www.kamatera.com/express/compute/
issues: https://www.github.com/Kamatera/ansible-collection-kamatera/issues
